name: Conflict Marker Check

on: [pull_request]

jobs:
  check-conflict-markers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for conflict markers
        run: |
          if grep -qE '<<<<<<<|=======|>>>>>>>' $(git ls-files); then
            echo "Conflict markers found."
            exit 1
          fi
