name: Merge Marker Check

on: [pull_request]

jobs:
  check-merge-markers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for merge markers in all files
        run: |
          if grep -rE '(^=======$|<<<<<<<|>>>>>>>)' --exclude-dir=.git --line-number .; then
            echo "Merge markers found."
            exit 1
          else
            echo "No merge markers found."
          fi
