name: Merge Marker Check on Changed Files

on: [pull_request]

jobs:
  check-merge-markers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get list of changed files
        id: files
        run: |
          echo "::set-output name=list::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

      - name: Check for merge markers in changed files
        run: |
          FILES=${{ steps.files.outputs.list }}
          EXCLUDE_PATTERNS=".github/workflows/* node_modules/* *.jpg *.gif *.png *.ttf *.woff *.eot"
          FLAG=0

          for FILE in $FILES; do
            if echo $EXCLUDE_PATTERNS | grep -q $FILE; then
              echo "SKIP $FILE"
              continue
            fi
            if grep -E '(^=======$|<<<<<<<|>>>>>>>)' $FILE --line-number -I; then
              echo "NG in $FILE"
              FLAG=1
            else
              echo "OK for $FILE"
            fi
          done

          if [ $FLAG -eq 1 ]; then
            exit 1
          fi

          echo "No merge markers found in changed files."
